FROM alpine:3.8
MAINTAINER Tom Fleming <tom@iotechsys.com>
RUN apk add --update --no-cache build-base wget gcc cmake make rpm-dev
RUN mkdir -p /libcbor/
WORKDIR /libcbor/
COPY . .
ENTRYPOINT /libcbor/scripts/entrypoint.sh
